#!/bin/sh

#timezone & loglevel
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

#system NTP
uci delete system.ntp
uci set system.ntp='timeserver'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'
uci add_list system.ntp.server='ntp1.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci commit system.ntp

#Default theme
uci set luci.main.mediaurlbase='/luci-static/bootstrap'	
uci commit luci

#Disable BBR
sed -i 's/net.ipv4.tcp_congestion_control=bbr/#net.ipv4.tcp_congestion_control=bbr/g' /etc/sysctl.d/12-tcp-bbr.conf
sysctl -p

#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci del uhttpd.main.listen_https
uci del uhttpd.main.cert
uci del uhttpd.main.key
uci commit uhttpd
/etc/init.d/uhttpd restart

#network
uci set network.lan.ipaddr='192.168.2.4'
uci del network.globals.ula_prefix
uci commit network
/etc/init.d/network restart

#firewall
uci set firewall.@zone[1].fullcone='1'
uci commit firewall

#upnp
uci set upnpd.config.enabled='0'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd

#dnsmasq
uci del dhcp.@dnsmasq[0].rebind_protection='1'
uci set dhcp.@dnsmasq[0].quietdhcp='1'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
uci commit dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

ln -sf /sbin/ip /usr/bin/ip
exit 0
