#!/bin/sh

#timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

#Default theme
uci set luci.main.mediaurlbase='/luci-static/bootstrap'	
uci commit luci

#irq
#uci set irqbalance.irqbalance.enabled=1
#uci commit irqbalance
#/etc/init.d/irqbalance restart

#Disable BBR
sed -i 's/net.ipv4.tcp_congestion_control=bbr/#net.ipv4.tcp_congestion_control=bbr/g' /etc/sysctl.d/12-tcp-bbr.conf
sysctl -p

#feed
sed -i '/openwrt_luci/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf	
sed -i '/openwrt_packages/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf	
sed -i '/openwrt_routing/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf	
sed -i '/openwrt_telephony/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/natelol/d' /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/lede,g' /etc/opkg/distfeeds.conf

#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci del uhttpd.main.listen_https
uci del uhttpd.main.cert
uci del uhttpd.main.key
uci commit uhttpd
/etc/init.d/uhttpd restart

#network
uci set network.lan.ipaddr='192.168.10.1'
uci commit network
/etc/init.d/network restart

#firewall
uci set firewall.@zone[1].fullcone='1'
uci commit firewall

#REDIRECT
sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

#upnp
uci set upnpd.config.igdv1='1'
uci set upnpd.config.enabled='0'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd

#dnsmasq
uci del dhcp.@dnsmasq[0].rebind_protection='1'
uci commit dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

ln -sf /sbin/ip /usr/bin/ip
sync; echo 3 > /proc/sys/vm/drop_caches
exit 0
